# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 10:29
from __future__ import unicode_literals

import csit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_ace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.ace_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_atm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.atm)),
            ],
        ),
        migrations.CreateModel(
            name='about_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.bank)),
            ],
        ),
        migrations.CreateModel(
            name='about_brite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.brite_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.cafe)),
            ],
        ),
        migrations.CreateModel(
            name='about_canteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.canteen)),
            ],
        ),
        migrations.CreateModel(
            name='about_comet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.comet_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_elite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.elite_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_energyclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.energyclub_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_fame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.fame_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.gym)),
            ],
        ),
        migrations.CreateModel(
            name='about_hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.hostel)),
            ],
        ),
        migrations.CreateModel(
            name='about_iclick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.iclick_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_institute', models.TextField()),
                ('about_institute_image', models.FileField(upload_to=csit.models.institute_img)),
            ],
        ),
        migrations.CreateModel(
            name='about_itclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.itclub_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_mea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mea_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_postoffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.postoffice)),
            ],
        ),
        migrations.CreateModel(
            name='about_saeee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.saeee_header)),
                ('notices', models.TextField()),
                ('activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ace_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.ace)),
            ],
        ),
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='applied_chemistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.chemistry_header)),
            ],
        ),
        migrations.CreateModel(
            name='applied_chemistry_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.chemistry)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='applied_maths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.maths_header)),
            ],
        ),
        migrations.CreateModel(
            name='applied_maths_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.maths)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='applied_physics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.physics_header)),
            ],
        ),
        migrations.CreateModel(
            name='applied_physics_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.physics)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='brite_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.brite)),
            ],
        ),
        migrations.CreateModel(
            name='chairman_speak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_speaks', models.TextField()),
                ('chairman_image', models.FileField(upload_to=csit.models.chairman)),
            ],
        ),
        migrations.CreateModel(
            name='comet_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.comet)),
            ],
        ),
        migrations.CreateModel(
            name='comp_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.cse)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='computer_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='computer_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.cse_header)),
            ],
        ),
        migrations.CreateModel(
            name='computer_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='computer_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='computer_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='director_speak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_speaks', models.TextField()),
                ('director_image', models.FileField(upload_to=csit.models.director)),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_heading', models.CharField(max_length=50)),
                ('downloads', models.FileField(upload_to=csit.models.dwnld)),
            ],
        ),
        migrations.CreateModel(
            name='ee_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.eee_header)),
            ],
        ),
        migrations.CreateModel(
            name='eee__notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eee__projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eee_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eee_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.eee)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='eee_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='elite_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.elite)),
            ],
        ),
        migrations.CreateModel(
            name='eminent_faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('qualifications', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=10)),
                ('image', models.FileField(upload_to=csit.models.eminent_faculty)),
            ],
        ),
        migrations.CreateModel(
            name='energyclub_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.energyclub)),
            ],
        ),
        migrations.CreateModel(
            name='eni_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eni_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.eni_header)),
            ],
        ),
        migrations.CreateModel(
            name='eni_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.eni)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='eni_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eni_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='eni_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='etnt_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='etnt_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.etnt_header)),
            ],
        ),
        migrations.CreateModel(
            name='etnt_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.etnt)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='etnt_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='etnt_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='etnt_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.TextField()),
                ('events_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='extra_notice_bigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('related_pic', models.FileField(upload_to=csit.models.extra_notice_biggers)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fame_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.fame)),
            ],
        ),
        migrations.CreateModel(
            name='firstslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=csit.models.fs)),
            ],
        ),
        migrations.CreateModel(
            name='governing_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governing_bodys', models.TextField()),
                ('governing_body_image', models.FileField(upload_to=csit.models.governing_body_img)),
            ],
        ),
        migrations.CreateModel(
            name='iclick_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.iclick)),
            ],
        ),
        migrations.CreateModel(
            name='information_technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.it_header)),
            ],
        ),
        migrations.CreateModel(
            name='it_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='it_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.it)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='it_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='it_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='it_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='itclub_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.itclub)),
            ],
        ),
        migrations.CreateModel(
            name='mea_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.mea)),
            ],
        ),
        migrations.CreateModel(
            name='mech_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.FileField(upload_to=csit.models.mech)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mech_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mech_header)),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechanical_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mechatronics_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mex_header)),
            ],
        ),
        migrations.CreateModel(
            name='membership_certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs', models.FileField(upload_to=csit.models.thumbs)),
            ],
        ),
        migrations.CreateModel(
            name='mex_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mex_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.mex)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mex_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mex_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mex_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mission_vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_visions', models.TextField()),
                ('mission_image', models.FileField(upload_to=csit.models.mission_img)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mtech_cse_header)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.mtech_computer)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_computer_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mtech_etnt_header)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.mtech_etnt)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_etnt_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mech_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mech_faculty_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=25)),
                ('faculty_designation', models.CharField(max_length=25)),
                ('faculty_experience', models.CharField(max_length=25)),
                ('faculty_area_of_interest', models.TextField()),
                ('faculty_image', models.ImageField(upload_to=csit.models.mtech_mechical)),
                ('publications', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mech_guest_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_lectures_name', models.CharField(max_length=25)),
                ('guest_lectures_event_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mech_notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mech_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mtech_mechanical_engg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_of_the_course', models.TextField()),
                ('strengths', models.TextField()),
                ('labs', models.TextField()),
                ('software', models.TextField()),
                ('image', models.FileField(upload_to=csit.models.mtech_mech_header)),
            ],
        ),
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='quality_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_policys', models.TextField()),
                ('quality_image', models.FileField(upload_to=csit.models.quality_policy_img)),
            ],
        ),
        migrations.CreateModel(
            name='saeee_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sem', models.CharField(max_length=3)),
                ('sec', models.CharField(max_length=3)),
                ('img', models.FileField(upload_to=csit.models.saeee)),
            ],
        ),
        migrations.CreateModel(
            name='secondslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to=csit.models.ss)),
            ],
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('batch', models.CharField(max_length=9)),
                ('branch', models.CharField(max_length=35)),
                ('message', models.TextField()),
                ('thumbs', models.FileField(upload_to=csit.models.testimonial_images)),
            ],
        ),
    ]
